# Generated by Django 6.0.6 on 2026-06-29 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('employees', '0005_alter_employee_department_alter_employee_employee_id_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['employee_id'], name='idx_employee_id'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['email'], name='idx_employee_email'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['department'], name='idx_department'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['joining_date'], name='idx_joining_date'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['salary'], name='idx_salary'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['department', 'salary'], name='idx_department_salary'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.CheckConstraint(condition=models.Q(('salary__gte', 10000)), name='salary_greater_than_10000'),
        ),
    ]
