# Generated by Django 6.0.7 on 2026-07-09 04:29

import django.db.models.deletion
import documents.models
import employees.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=150)),
                ('document_type', models.CharField(choices=[('RESUME', 'Resume'), ('AADHAAR', 'Aadhaar'), ('PAN', 'PAN'), ('DEGREE_CERTIFICATE', 'Degree Certificate'), ('EXPERIENCE_CERTIFICATE', 'Experience Certificate'), ('OFFER_LETTER', 'Offer Letter'), ('OTHER', 'Other')], max_length=30)),
                ('file', models.FileField(upload_to=documents.models.employee_document_path, validators=[employees.validators.validate_document_file])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='employees.employee')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
