# Generated by Django 6.0.7 on 2026-07-08 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_identifier', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('action', models.CharField(choices=[('LOGIN_SUCCESS', 'Login Success'), ('LOGIN_FAILURE', 'Login Failure'), ('LOGOUT', 'Logout'), ('TOKEN_REFRESH', 'Token Refresh'), ('TOKEN_BLACKLISTED', 'Token Blacklisted'), ('PASSWORD_CHANGE', 'Password Change'), ('PASSWORD_RESET_REQUESTED', 'Password Reset Requested'), ('PASSWORD_RESET_COMPLETED', 'Password Reset Completed'), ('UNAUTHORIZED_ACCESS', 'Unauthorized Access'), ('PERMISSION_DENIED', 'Permission Denied'), ('RATE_LIMIT_EXCEEDED', 'Rate Limit Exceeded'), ('FILE_UPLOAD_REJECTED', 'File Upload Rejected')], max_length=40)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('WARNING', 'Warning')], max_length=10)),
                ('path', models.CharField(blank=True, max_length=255)),
                ('detail', models.CharField(blank=True, max_length=512)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['action', '-timestamp'], name='logs_securi_action_8c31b6_idx'), models.Index(fields=['user', '-timestamp'], name='logs_securi_user_id_dd804f_idx'), models.Index(fields=['status', '-timestamp'], name='logs_securi_status_476328_idx')],
            },
        ),
    ]
